import { Advice, Bakery, Blogr, Bookmarks, Clipboard, ColunmsCard, DevFolio, Easybank, Fokir, Huddle, Insure, Loopstudios, Movies, 
News, NFT, Notes, Notfication, OrderSummary, Piggy, Price, Profile, Restaurant, Result, Signup, Simone, Stats,
Sunnyside, Testimonials, Weather, BakeryFull, BlogrFullPage, ClipboardPageFull, DevFolioFull, BlogFull, EasyBankFullPage,
FokirFull, HuddleFullPage, insureFullPage, loopstudiosFullPage, MoviesAbout, MoviesHome, SingleMovie, MoviesSearch,
NewsHomePage, NFTCard, NotesFullPage, NotifactionFullPage, OrderSummaryComponent, RestaurantFullPage, ResultSummaryComponent,
PiggyFullPage, ThreeColumnCards, PriceComponent, ProfileCard, SignUpPage, SimoneFullPage, StatsPreviewCard, SunnysideAgencyFullPage,
WeatherFullPage, TestimonialsSection, AdviceGenerator,} from "./imgs";

export const projectsOfMyWork = [
    {
        id: `work-1`,
        title: `Trending Movies`,
        toolUsed: `React.js - Bootstrap - Axois (API) -  Jwt-decode - JOI - API From https://www.themoviedb.org/ - SAP`,
        liveDemo: `https://mohamed-emad97.github.io/Trending-Movies/#/register`,
        gitRepo: `https://github.com/Mohamed-Emad97/Trending-Movies`,
        thumnail: Movies,
        imgs: [SingleMovie, MoviesAbout, MoviesHome, MoviesSearch],
    },
    {
        id: `work-2`,
        title: `Notes`,
        toolUsed: `React.js - Bootstrap - Axois (API) - Jwt-decode - Sweetalert - Jquery - Fontawesome - SAP`,
        liveDemo: `https://mohamed-emad97.github.io/Notes-App/`,
        gitRepo: `https://github.com/Mohamed-Emad97/Notes-App`,
        thumnail: Notes,
        imgs: [NotesFullPage],
    },
    {
        id: `work-3`,
        title: `Restaurant`,
        toolUsed: `React.js - Bootstrap - scss - FontAwesome`,
        liveDemo: `https://mohamed-emad97.github.io/Restaurant-Template/`,
        gitRepo: `https://github.com/Mohamed-Emad97/Restaurant-Template/tree/main/src`,
        thumnail: Restaurant,
        imgs: [RestaurantFullPage],
    },
    {
        id: `work-4`,
        title: `SIMONE-TEMPLATE`,
        toolUsed: `JavaScript - SCSS - Bootstrap - JQuery - Owl.js - Typed.js - FontAwesome`,
        liveDemo: `https://mohamed-emad97.github.io/Simone-Template/`,
        gitRepo: `https://github.com/Mohamed-Emad97/Simone-Template`,
        thumnail: Simone,
        imgs: [SimoneFullPage],
    },
    {
        id: `work-5`,
        title: `Bakery-Template`,
        toolUsed: `JavaScript - CSS3 - HTML5 - Font Awesome - Bootstrap`,
        liveDemo: `https://mohamed-emad97.github.io/Bakery-Template/`,
        gitRepo: `https://github.com/Mohamed-Emad97/Bakery-Template`,
        thumnail: Bakery,
        imgs: [BakeryFull],
    },
    {
        id: `work-6`,
        title: `Weather-Web-App`,
        toolUsed: `JavaScript - Bootstrap - CSS3 - HTML5 - Font Awesome - AJAX -  used WeatherApi from https://www.weatherapi.com/`,
        liveDemo: `#`,
        gitRepo: `https://github.com/Mohamed-Emad97/Weather-Web-App`,
        thumnail: Weather,
        imgs: [WeatherFullPage],
    },
    {
        id: `work-7`,
        title: `Piggy-Template`,
        toolUsed: `HTML5 - CSS3 - Bootstrap`,
        liveDemo: `https://mohamed-emad97.github.io/Piggy-Template/`,
        gitRepo: `https://github.com/Mohamed-Emad97/Piggy-Template`,
        thumnail: Piggy,
        imgs: [PiggyFullPage],
    },
    {
        id: `work-8`,
        title: `DevFolio-Template`,
        toolUsed: `JavaScript - SCSS - Bootstrap - JQuery - Owl.js - Typed.js - FontAwesome`,
        liveDemo: `https://mohamed-emad97.github.io/DevFolio-Template/`,
        gitRepo: `https://github.com/Mohamed-Emad97/DevFolio-Template`,
        thumnail: DevFolio,
        imgs: [DevFolioFull, BlogFull],
    },
    {
        id: `work-9`,
        title: `Fokir-Template`,
        toolUsed: `JavaScript - SCSS - Bootstrap - JQuery - Owl.js - Typed.js - FontAwesome`,
        liveDemo: `https://mohamed-emad97.github.io/Fokir-Template/`,
        gitRepo: `https://github.com/Mohamed-Emad97/Fokir-Template`,
        thumnail: Fokir,
        imgs: [FokirFull],
    },
    {
        id: `work-10`,
        title: `Book-Marks`,
        toolUsed: `JavaScript - CSS3 - Bootstrap - HTML5`,
        liveDemo: `https://mohamed-emad97.github.io/Book-Marks/`,
        gitRepo: `https://github.com/Mohamed-Emad97/Book-Marks`,
        thumnail: Bookmarks,
        imgs: [Bookmarks],
    },
    {
        id: `work-11`,
        title: `Simple-sign-up`,
        toolUsed: `JavaScript - SCSS - Bootstrap - HTML5 - Yup - Formik - React.js`,
        liveDemo: `https://mohamed-emad97.github.io/Simple-sign-up/`,
        gitRepo: `https://github.com/Mohamed-Emad97/Simple-sign-up`,
        thumnail: Signup,
        imgs: [SignUpPage],
    },
];


export const projectsOfFrontEnd = [
    {
        id: `1_project`,
        title: `News Home Page`,
        toolUsed: `React.js - Bootstrap - SASS - SAP`,
        liveDemo: `https://mohamed-emad97.github.io/News-Home-Page/`,
        gitRepo: `https://github.com/Mohamed-Emad97/News-Home-Page`,
        thumnail: News,
        imgs: [NewsHomePage],
    },
    {
        id: '2_project',
        title: `Clip Board Landing Page`,
        toolUsed: `React.js - Bootstrap - SASS - Fontawesome`,
        liveDemo: `https://github.com/Mohamed-Emad97/clipboard-landing-page`,
        gitRepo: `https://github.com/Mohamed-Emad97/clipboard-landing-page`,
        thumnail: Clipboard,
        imgs: [ClipboardPageFull],
    },
    {
        id: '3_project',
        title: `Notfication`,
        toolUsed: `React.js - Bootstrap - SASS - Fontawesome`,
        liveDemo: `https://mohamed-emad97.github.io/Notfication/`,
        gitRepo: `https://github.com/Mohamed-Emad97/Notfication`,
        thumnail: Notfication,
        imgs: [NotifactionFullPage],
    },
    {
        id: '4_project',
        title: `NTF Preview Card`,
        toolUsed: `React.js - Bootstrap - SASS - Fontawesome`,
        liveDemo: `https://mohamed-emad97.github.io/nft-preview-card-component/`,
        gitRepo: `https://github.com/Mohamed-Emad97/nft-preview-card-component`,
        thumnail: NFT,
        imgs: [NFTCard],
    },
    {
        id: '5_project',
        title: `Insure Landing Page`,
        toolUsed: `React.js - Bootstrap - SASS - Fontawesome`,
        liveDemo: `https://mohamed-emad97.github.io/Insure_landing_Page/`,
        gitRepo: `https://github.com/Mohamed-Emad97/Insure_landing_Page`,
        thumnail: Insure,
        imgs: [insureFullPage],
    },
    {
        id: '6_project',
        title: `Blogr Landing Page`,
        toolUsed: `React.js - Bootstrap - SASS - Fontawesome`,
        liveDemo: `https://mohamed-emad97.github.io/blogr-landing-page-main/`,
        gitRepo: `https://github.com/Mohamed-Emad97/blogr-landing-page-main`,
        thumnail: Blogr,
        imgs: [BlogrFullPage],
    },
    {
        id: '7_project',
        title: `Loopstudios Landing Page`,
        toolUsed: `React.js - Bootstrap - SASS - Fontawesome`,
        liveDemo: `https://mohamed-emad97.github.io/loopstudios-landing-page-main/`,
        gitRepo: `https://github.com/Mohamed-Emad97/loopstudios-landing-page-main`,
        thumnail: Loopstudios,
        imgs: [loopstudiosFullPage],
    },
    {
        id: '8_project',
        title: `Single Price Grid`,
        toolUsed: `React.js - Bootstrap - SASS`,
        liveDemo: `https://mohamed-emad97.github.io/single-price-grid-component-master/`,
        gitRepo: `https://github.com/Mohamed-Emad97/single-price-grid-component-master`,
        thumnail: Price,
        imgs: [PriceComponent],
    },
    {
        id: '9_project',
        title: `Testimionls Grid Section`,
        toolUsed: `React.js - Bootstrap - SASS`,
        liveDemo: `https://mohamed-emad97.github.io/testimonials-grid-section-main/`,
        gitRepo: `https://github.com/Mohamed-Emad97/testimonials-grid-section-main`,
        thumnail: Testimonials,
        imgs: [TestimonialsSection],
    },
    {
        id: '10_project',
        title: `Stats Preview Card`,
        toolUsed: `React.js - Bootstrap - SASS`,
        liveDemo: `https://mohamed-emad97.github.io/stats-preview-card-component-main/`,
        gitRepo: `https://github.com/Mohamed-Emad97/stats-preview-card-component-main`,
        thumnail: Stats,
        imgs: [StatsPreviewCard],
    },
    {
        id: '11_project',
        title: `Order Summary Component`,
        toolUsed: `React.js - Bootstrap - SASS - Fontawesome`,
        liveDemo: `https://mohamed-emad97.github.io/order-summary-component-main/`,
        gitRepo: `https://github.com/Mohamed-Emad97/order-summary-component-main`,
        thumnail: OrderSummary,
        imgs: [OrderSummaryComponent],
    },
    {
        id: '12_project',
        title: `Result Summary Component`,
        toolUsed: `React.js - Bootstrap - SASS - Fontawesome`,
        liveDemo: `https://mohamed-emad97.github.io/Result-summary-component/`,
        gitRepo: `https://github.com/Mohamed-Emad97/Result-summary-component`,
        thumnail: Result,
        imgs: [ResultSummaryComponent],
    },
    {
        id: '13_project',
        title: `Sunnyside Agency Landing`,
        toolUsed: `React.js - Bootstrap - SASS - Fontawesome`,
        liveDemo: `https://mohamed-emad97.github.io/Sunnyside-agency-landing-page/`,
        gitRepo: `https://github.com/Mohamed-Emad97/Sunnyside-agency-landing-page`,
        thumnail: Sunnyside,
        imgs: [SunnysideAgencyFullPage],
    },
    {
        id: '14_project',
        title: `Easy Bank Landing`,
        toolUsed: `React.js - Bootstrap - SASS - Fontawesome`,
        liveDemo: `https://mohamed-emad97.github.io/Easy_Bank/`,
        gitRepo: `https://github.com/Mohamed-Emad97/Easy_Bank`,
        thumnail: Easybank,
        imgs: [EasyBankFullPage],
    },
    {
        id: '15_project',
        title: `Advice Generator`,
        toolUsed: `React.js - Bootstrap - SASS - Fontawesome - API (Axios)`,
        liveDemo: `https://mohamed-emad97.github.io/Advice_generator_app/`,
        gitRepo: `https://github.com/Mohamed-Emad97/Advice_generator_app`,
        thumnail: Advice,
        imgs: [AdviceGenerator],
    },
    {
        id: '16_project',
        title: `Profile Card`,
        toolUsed: `React.js - Bootstrap - SASS`,
        liveDemo: `https://mohamed-emad97.github.io/Profile_Card/`,
        gitRepo: `https://github.com/Mohamed-Emad97/Profile_Card`,
        thumnail: Profile,
        imgs: [ProfileCard],
    },
    {
        id: '17_project',
        title: `Three Column Preview Cards`,
        toolUsed: `React.js - Bootstrap - SASS - Fontawesome`,
        liveDemo: `https://mohamed-emad97.github.io/3-column-preview-card-component-main/`,
        gitRepo: `https://github.com/Mohamed-Emad97/3-column-preview-card-component-main`,
        thumnail: ColunmsCard,
        imgs: [ThreeColumnCards],
    },
    {
        id: '18_project',
        title: `Huddle Landing Page`,
        toolUsed: `React.js - Bootstrap - SASS - Fontawesome`,
        liveDemo: `https://mohamed-emad97.github.io/Huddle-Landing-Page/`,
        gitRepo: `https://github.com/Mohamed-Emad97/Huddle-Landing-Page`,
        thumnail: Huddle,
        imgs: [HuddleFullPage],
    },
];